/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all folders
 */
export declare const ListFoldersResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
}, {
    id: string;
    name: string;
    createdAt: Date;
}>;
export declare const ListFoldersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
}, {
    id: string;
    name: string;
    createdAt: Date;
}>, "many">;
/**
 * @summary Create a folder
 */
export declare const CreateFolderBody: zod.ZodObject<{
    name: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
}, {
    name: string;
}>;
/**
 * Returns all equipment items
 * @summary List all equipment
 */
export declare const ListEquipmentResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastSeen: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    lastStatus: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastMaintenanceDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>;
export declare const ListEquipmentResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastSeen: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    lastStatus: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastMaintenanceDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>, "many">;
/**
 * Creates a new equipment item with an auto-generated ID
 * @summary Create equipment item
 */
export declare const CreateEquipmentBody: zod.ZodObject<{
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
}, {
    name: string;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
}>;
/**
 * @summary Get equipment by ID
 */
export declare const GetEquipmentParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetEquipmentResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastSeen: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    lastStatus: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastMaintenanceDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>;
/**
 * Updates equipment profile fields (serial number, model, manufacturer, purchase date, location, maintenance interval)
 * @summary Update equipment profile
 */
export declare const UpdateEquipmentParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const UpdateEquipmentBody: zod.ZodObject<{
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>;
export declare const UpdateEquipmentResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastSeen: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    lastStatus: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastMaintenanceDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>;
/**
 * Permanently deletes an equipment item and its scan logs
 * @summary Delete equipment item
 */
export declare const DeleteEquipmentParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
/**
 * Permanently deletes multiple equipment items and their scan/transfer logs.
 * @summary Delete multiple equipment items
 */
export declare const BulkDeleteEquipmentBody: zod.ZodObject<{
    ids: zod.ZodArray<zod.ZodString, "many">;
}, "strip", zod.ZodTypeAny, {
    ids: string[];
}, {
    ids: string[];
}>;
export declare const BulkDeleteEquipmentResponse: zod.ZodObject<{
    affected: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    affected: number;
}, {
    affected: number;
}>;
/**
 * Reassigns multiple equipment items to the specified folder, logging transfers.
 * @summary Move multiple equipment items to a folder
 */
export declare const BulkMoveEquipmentBody: zod.ZodObject<{
    ids: zod.ZodArray<zod.ZodString, "many">;
    folderId: zod.ZodNullable<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    folderId: string | null;
    ids: string[];
}, {
    folderId: string | null;
    ids: string[];
}>;
export declare const BulkMoveEquipmentResponse: zod.ZodObject<{
    affected: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    affected: number;
}, {
    affected: number;
}>;
/**
 * Updates lastSeen, lastStatus, and (if maintenance) lastMaintenanceDate; appends log
 * @summary Record a QR scan with status
 */
export declare const ScanEquipmentParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const ScanEquipmentBody: zod.ZodObject<{
    status: zod.ZodEnum<["ok", "issue", "maintenance"]>;
    note: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    photoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "ok" | "issue" | "maintenance";
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}, {
    status: "ok" | "issue" | "maintenance";
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}>;
export declare const ScanEquipmentResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    serialNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    model: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    manufacturer: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    purchaseDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    folderId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastSeen: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    lastStatus: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastMaintenanceDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maintenanceIntervalDays: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}, {
    id: string;
    name: string;
    createdAt: Date;
    serialNumber?: string | null | undefined;
    model?: string | null | undefined;
    manufacturer?: string | null | undefined;
    purchaseDate?: Date | null | undefined;
    location?: string | null | undefined;
    folderId?: string | null | undefined;
    lastSeen?: Date | null | undefined;
    lastStatus?: string | null | undefined;
    lastMaintenanceDate?: Date | null | undefined;
    maintenanceIntervalDays?: number | null | undefined;
}>;
/**
 * @summary Get scan history for equipment
 */
export declare const GetEquipmentLogsParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetEquipmentLogsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    equipmentId: zod.ZodString;
    status: zod.ZodString;
    note: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    photoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    timestamp: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    equipmentId: string;
    timestamp: Date;
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}, {
    status: string;
    id: string;
    equipmentId: string;
    timestamp: Date;
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}>;
export declare const GetEquipmentLogsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    equipmentId: zod.ZodString;
    status: zod.ZodString;
    note: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    photoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    timestamp: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    equipmentId: string;
    timestamp: Date;
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}, {
    status: string;
    id: string;
    equipmentId: string;
    timestamp: Date;
    note?: string | null | undefined;
    photoUrl?: string | null | undefined;
}>, "many">;
/**
 * Returns chronological list of folder transfers for this equipment item.
 * @summary Get transfer history for equipment
 */
export declare const GetEquipmentTransfersParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetEquipmentTransfersResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    equipmentId: zod.ZodString;
    fromFolderName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    toFolderName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    timestamp: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    equipmentId: string;
    timestamp: Date;
    fromFolderName?: string | null | undefined;
    toFolderName?: string | null | undefined;
}, {
    id: string;
    equipmentId: string;
    timestamp: Date;
    fromFolderName?: string | null | undefined;
    toFolderName?: string | null | undefined;
}>;
export declare const GetEquipmentTransfersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    equipmentId: zod.ZodString;
    fromFolderName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    toFolderName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    timestamp: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    equipmentId: string;
    timestamp: Date;
    fromFolderName?: string | null | undefined;
    toFolderName?: string | null | undefined;
}, {
    id: string;
    equipmentId: string;
    timestamp: Date;
    fromFolderName?: string | null | undefined;
    toFolderName?: string | null | undefined;
}>, "many">;
/**
 * Returns scan logs across all equipment, most recent first, with cursor-based pagination.
 * @summary Global activity feed
 */
export declare const ListLogsQueryParams: zod.ZodObject<{
    cursor: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    cursor?: string | undefined;
}, {
    cursor?: string | undefined;
}>;
export declare const ListLogsResponse: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        equipmentId: zod.ZodString;
        equipmentName: zod.ZodString;
        status: zod.ZodString;
        note: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        photoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        timestamp: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        equipmentId: string;
        timestamp: Date;
        equipmentName: string;
        note?: string | null | undefined;
        photoUrl?: string | null | undefined;
    }, {
        status: string;
        id: string;
        equipmentId: string;
        timestamp: Date;
        equipmentName: string;
        note?: string | null | undefined;
        photoUrl?: string | null | undefined;
    }>, "many">;
    nextCursor: zod.ZodNullable<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    items: {
        status: string;
        id: string;
        equipmentId: string;
        timestamp: Date;
        equipmentName: string;
        note?: string | null | undefined;
        photoUrl?: string | null | undefined;
    }[];
    nextCursor: string | null;
}, {
    items: {
        status: string;
        id: string;
        equipmentId: string;
        timestamp: Date;
        equipmentName: string;
        note?: string | null | undefined;
        photoUrl?: string | null | undefined;
    }[];
    nextCursor: string | null;
}>;
/**
 * Returns aggregated analytics data including scan activity over 30 days, equipment status breakdown, maintenance compliance, and top problem equipment.
 * @summary Get dashboard analytics summary
 */
export declare const GetAnalyticsSummaryResponse: zod.ZodObject<{
    totalEquipment: zod.ZodNumber;
    statusBreakdown: zod.ZodObject<{
        ok: zod.ZodNumber;
        issue: zod.ZodNumber;
        overdue: zod.ZodNumber;
        inactive: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        ok: number;
        issue: number;
        overdue: number;
        inactive: number;
    }, {
        ok: number;
        issue: number;
        overdue: number;
        inactive: number;
    }>;
    maintenanceComplianceRate: zod.ZodNumber;
    scanActivity: zod.ZodArray<zod.ZodObject<{
        date: zod.ZodString;
        count: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        date: string;
        count: number;
    }, {
        date: string;
        count: number;
    }>, "many">;
    topProblemEquipment: zod.ZodArray<zod.ZodObject<{
        equipmentId: zod.ZodString;
        name: zod.ZodString;
        issueCount: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        equipmentId: string;
        issueCount: number;
    }, {
        name: string;
        equipmentId: string;
        issueCount: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalEquipment: number;
    statusBreakdown: {
        ok: number;
        issue: number;
        overdue: number;
        inactive: number;
    };
    maintenanceComplianceRate: number;
    scanActivity: {
        date: string;
        count: number;
    }[];
    topProblemEquipment: {
        name: string;
        equipmentId: string;
        issueCount: number;
    }[];
}, {
    totalEquipment: number;
    statusBreakdown: {
        ok: number;
        issue: number;
        overdue: number;
        inactive: number;
    };
    maintenanceComplianceRate: number;
    scanActivity: {
        date: string;
        count: number;
    }[];
    topProblemEquipment: {
        name: string;
        equipmentId: string;
        issueCount: number;
    }[];
}>;
/**
 * Returns a presigned GCS URL for direct upload. The client sends JSON
metadata here, then uploads the file directly to the returned URL.

 * @summary Request a presigned URL for file upload
 */
export declare const RequestUploadUrlBody: zod.ZodObject<{
    name: zod.ZodString;
    size: zod.ZodNumber;
    contentType: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    size: number;
    contentType: string;
}, {
    name: string;
    size: number;
    contentType: string;
}>;
export declare const RequestUploadUrlResponse: zod.ZodObject<{
    uploadURL: zod.ZodString;
    objectPath: zod.ZodString;
    metadata: zod.ZodOptional<zod.ZodObject<{
        name: zod.ZodString;
        size: zod.ZodNumber;
        contentType: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        size: number;
        contentType: string;
    }, {
        name: string;
        size: number;
        contentType: string;
    }>>;
}, "strip", zod.ZodTypeAny, {
    uploadURL: string;
    objectPath: string;
    metadata?: {
        name: string;
        size: number;
        contentType: string;
    } | undefined;
}, {
    uploadURL: string;
    objectPath: string;
    metadata?: {
        name: string;
        size: number;
        contentType: string;
    } | undefined;
}>;
/**
 * @summary Serve a public asset from PUBLIC_OBJECT_SEARCH_PATHS
 */
export declare const GetPublicObjectParams: zod.ZodObject<{
    filePath: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    filePath: string;
}, {
    filePath: string;
}>;
/**
 * @summary Serve an object entity from PRIVATE_OBJECT_DIR
 */
export declare const GetStorageObjectParams: zod.ZodObject<{
    objectPath: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    objectPath: string;
}, {
    objectPath: string;
}>;
//# sourceMappingURL=api.d.ts.map