/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
export interface TransferLog {
    id: string;
    equipmentId: string;
    fromFolderName?: string | null;
    toFolderName?: string | null;
    timestamp: Date;
}
//# sourceMappingURL=transferLog.d.ts.map