/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateEquipmentRequest {
  /** Maintenance interval in days; null to clear */
  maintenanceIntervalDays?: number | null;
  /** Serial number */
  serialNumber?: string | null;
  /** Model name/number */
  model?: string | null;
  /** Manufacturer or brand */
  manufacturer?: string | null;
  /** Purchase date */
  purchaseDate?: Date | null;
  /** Physical location */
  location?: string | null;
  /** Equipment category */
  category?: string | null;
  /** Folder to assign the equipment to; null to unassign */
  folderId?: string | null;
}
