/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRecordRole } from "./userRecordRole";

export interface UserRecord {
  /** Clerk user ID (primary key) */
  clerkId: string;
  /** User role */
  role: UserRecordRole;
  /** When the user first signed in */
  createdAt: Date;
}
