/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all folders
 */
export const ListFoldersResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListFoldersResponse = zod.array(ListFoldersResponseItem);

/**
 * @summary Create a folder
 */

export const CreateFolderBody = zod.object({
  name: zod.string().min(1),
});

/**
 * Returns all equipment items
 * @summary List all equipment
 */
export const ListEquipmentResponseItem = zod.object({
  id: zod.string().describe("Auto-generated unique ID"),
  name: zod.string().describe("Equipment name"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce
    .date()
    .nullish()
    .describe("Date the equipment was purchased"),
  location: zod
    .string()
    .nullish()
    .describe("Physical location of the equipment"),
  category: zod
    .string()
    .nullish()
    .describe(
      "Equipment category (e.g. Surgical Instruments, Diagnostic Imaging)",
    ),
  folderId: zod.string().nullish().describe("Folder this equipment belongs to"),
  lastSeen: zod.coerce
    .date()
    .nullish()
    .describe("Last time the QR code was scanned"),
  lastStatus: zod
    .string()
    .nullish()
    .describe("Status set at last scan (ok, issue, maintenance)"),
  lastMaintenanceDate: zod.coerce
    .date()
    .nullish()
    .describe("Date of last maintenance scan"),
  maintenanceIntervalDays: zod
    .number()
    .nullish()
    .describe(
      "How often maintenance should occur (days); null means not configured",
    ),
  createdAt: zod.coerce.date().describe("When the equipment was created"),
});
export const ListEquipmentResponse = zod.array(ListEquipmentResponseItem);

/**
 * Creates a new equipment item with an auto-generated ID
 * @summary Create equipment item
 */
export const CreateEquipmentBody = zod.object({
  name: zod.string().describe("Equipment name"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce.date().nullish().describe("Purchase date"),
  location: zod.string().nullish().describe("Physical location"),
  category: zod.string().nullish().describe("Equipment category"),
  folderId: zod
    .string()
    .nullish()
    .describe("Optional folder to assign the equipment to"),
});

/**
 * @summary Get equipment by ID
 */
export const GetEquipmentParams = zod.object({
  id: zod.coerce.string(),
});

export const GetEquipmentResponse = zod.object({
  id: zod.string().describe("Auto-generated unique ID"),
  name: zod.string().describe("Equipment name"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce
    .date()
    .nullish()
    .describe("Date the equipment was purchased"),
  location: zod
    .string()
    .nullish()
    .describe("Physical location of the equipment"),
  category: zod
    .string()
    .nullish()
    .describe(
      "Equipment category (e.g. Surgical Instruments, Diagnostic Imaging)",
    ),
  folderId: zod.string().nullish().describe("Folder this equipment belongs to"),
  lastSeen: zod.coerce
    .date()
    .nullish()
    .describe("Last time the QR code was scanned"),
  lastStatus: zod
    .string()
    .nullish()
    .describe("Status set at last scan (ok, issue, maintenance)"),
  lastMaintenanceDate: zod.coerce
    .date()
    .nullish()
    .describe("Date of last maintenance scan"),
  maintenanceIntervalDays: zod
    .number()
    .nullish()
    .describe(
      "How often maintenance should occur (days); null means not configured",
    ),
  createdAt: zod.coerce.date().describe("When the equipment was created"),
});

/**
 * Updates equipment profile fields (serial number, model, manufacturer, purchase date, location, maintenance interval)
 * @summary Update equipment profile
 */
export const UpdateEquipmentParams = zod.object({
  id: zod.coerce.string(),
});

export const UpdateEquipmentBody = zod.object({
  maintenanceIntervalDays: zod
    .number()
    .nullish()
    .describe("Maintenance interval in days; null to clear"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce.date().nullish().describe("Purchase date"),
  location: zod.string().nullish().describe("Physical location"),
  category: zod.string().nullish().describe("Equipment category"),
  folderId: zod
    .string()
    .nullish()
    .describe("Folder to assign the equipment to; null to unassign"),
});

export const UpdateEquipmentResponse = zod.object({
  id: zod.string().describe("Auto-generated unique ID"),
  name: zod.string().describe("Equipment name"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce
    .date()
    .nullish()
    .describe("Date the equipment was purchased"),
  location: zod
    .string()
    .nullish()
    .describe("Physical location of the equipment"),
  category: zod
    .string()
    .nullish()
    .describe(
      "Equipment category (e.g. Surgical Instruments, Diagnostic Imaging)",
    ),
  folderId: zod.string().nullish().describe("Folder this equipment belongs to"),
  lastSeen: zod.coerce
    .date()
    .nullish()
    .describe("Last time the QR code was scanned"),
  lastStatus: zod
    .string()
    .nullish()
    .describe("Status set at last scan (ok, issue, maintenance)"),
  lastMaintenanceDate: zod.coerce
    .date()
    .nullish()
    .describe("Date of last maintenance scan"),
  maintenanceIntervalDays: zod
    .number()
    .nullish()
    .describe(
      "How often maintenance should occur (days); null means not configured",
    ),
  createdAt: zod.coerce.date().describe("When the equipment was created"),
});

/**
 * Permanently deletes an equipment item and its scan logs
 * @summary Delete equipment item
 */
export const DeleteEquipmentParams = zod.object({
  id: zod.coerce.string(),
});

/**
 * Permanently deletes multiple equipment items and their scan/transfer logs.
 * @summary Delete multiple equipment items
 */

export const BulkDeleteEquipmentBody = zod.object({
  ids: zod.array(zod.string()).min(1),
});

export const BulkDeleteEquipmentResponse = zod.object({
  affected: zod.number().describe("Number of items affected"),
});

/**
 * Reassigns multiple equipment items to the specified folder, logging transfers.
 * @summary Move multiple equipment items to a folder
 */

export const BulkMoveEquipmentBody = zod.object({
  ids: zod.array(zod.string()).min(1),
  folderId: zod
    .string()
    .nullable()
    .describe("Target folder ID; null to unassign from any folder"),
});

export const BulkMoveEquipmentResponse = zod.object({
  affected: zod.number().describe("Number of items affected"),
});

/**
 * Updates lastSeen, lastStatus, and (if maintenance) lastMaintenanceDate; appends log
 * @summary Record a QR scan with status
 */
export const ScanEquipmentParams = zod.object({
  id: zod.coerce.string(),
});

export const ScanEquipmentBody = zod.object({
  status: zod
    .enum(["ok", "issue", "maintenance", "sterilized"])
    .describe("Status selected after scanning"),
  note: zod.string().nullish().describe("Optional note about the scan"),
  photoUrl: zod
    .string()
    .nullish()
    .describe("Optional photo URL from object storage"),
});

export const ScanEquipmentResponse = zod.object({
  id: zod.string().describe("Auto-generated unique ID"),
  name: zod.string().describe("Equipment name"),
  serialNumber: zod.string().nullish().describe("Serial number"),
  model: zod.string().nullish().describe("Model name\/number"),
  manufacturer: zod.string().nullish().describe("Manufacturer or brand"),
  purchaseDate: zod.coerce
    .date()
    .nullish()
    .describe("Date the equipment was purchased"),
  location: zod
    .string()
    .nullish()
    .describe("Physical location of the equipment"),
  category: zod
    .string()
    .nullish()
    .describe(
      "Equipment category (e.g. Surgical Instruments, Diagnostic Imaging)",
    ),
  folderId: zod.string().nullish().describe("Folder this equipment belongs to"),
  lastSeen: zod.coerce
    .date()
    .nullish()
    .describe("Last time the QR code was scanned"),
  lastStatus: zod
    .string()
    .nullish()
    .describe("Status set at last scan (ok, issue, maintenance)"),
  lastMaintenanceDate: zod.coerce
    .date()
    .nullish()
    .describe("Date of last maintenance scan"),
  maintenanceIntervalDays: zod
    .number()
    .nullish()
    .describe(
      "How often maintenance should occur (days); null means not configured",
    ),
  createdAt: zod.coerce.date().describe("When the equipment was created"),
});

/**
 * @summary Get scan history for equipment
 */
export const GetEquipmentLogsParams = zod.object({
  id: zod.coerce.string(),
});

export const GetEquipmentLogsResponseItem = zod.object({
  id: zod.string(),
  equipmentId: zod.string(),
  status: zod.string(),
  note: zod.string().nullish(),
  photoUrl: zod.string().nullish(),
  scannedBy: zod
    .string()
    .nullish()
    .describe("Clerk user ID of the user who performed the scan"),
  timestamp: zod.coerce.date(),
});
export const GetEquipmentLogsResponse = zod.array(GetEquipmentLogsResponseItem);

/**
 * Returns chronological list of folder transfers for this equipment item.
 * @summary Get transfer history for equipment
 */
export const GetEquipmentTransfersParams = zod.object({
  id: zod.coerce.string(),
});

export const GetEquipmentTransfersResponseItem = zod.object({
  id: zod.string(),
  equipmentId: zod.string(),
  fromFolderName: zod.string().nullish(),
  toFolderName: zod.string().nullish(),
  timestamp: zod.coerce.date(),
});
export const GetEquipmentTransfersResponse = zod.array(
  GetEquipmentTransfersResponseItem,
);

/**
 * Returns scan logs across all equipment, most recent first, with cursor-based pagination.
 * @summary Global activity feed
 */
export const ListLogsQueryParams = zod.object({
  cursor: zod.coerce
    .string()
    .optional()
    .describe(
      "Opaque pagination cursor returned as nextCursor from a previous response. Do not construct manually.",
    ),
});

export const ListLogsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string(),
      equipmentId: zod.string(),
      equipmentName: zod.string(),
      status: zod.string(),
      note: zod.string().nullish(),
      photoUrl: zod.string().nullish(),
      timestamp: zod.coerce.date(),
    }),
  ),
  nextCursor: zod.string().nullable(),
});

/**
 * Returns aggregated analytics data including scan activity over 30 days, equipment status breakdown, maintenance compliance, and top problem equipment.
 * @summary Get dashboard analytics summary
 */
export const GetAnalyticsSummaryResponse = zod.object({
  totalEquipment: zod.number(),
  statusBreakdown: zod.object({
    ok: zod.number(),
    issue: zod.number(),
    overdue: zod.number(),
    inactive: zod.number(),
  }),
  maintenanceComplianceRate: zod
    .number()
    .describe("Percentage of equipment with up-to-date maintenance (0-100)"),
  scanActivity: zod.array(
    zod.object({
      date: zod.string(),
      count: zod.number(),
    }),
  ),
  topProblemEquipment: zod.array(
    zod.object({
      equipmentId: zod.string(),
      name: zod.string(),
      issueCount: zod.number(),
    }),
  ),
});

/**
 * Returns a presigned GCS URL for direct upload. The client sends JSON
metadata here, then uploads the file directly to the returned URL.

 * @summary Request a presigned URL for file upload
 */

export const RequestUploadUrlBody = zod.object({
  name: zod.string().min(1).describe("Original file name."),
  size: zod.number().min(1).describe("File size in bytes."),
  contentType: zod.string().min(1).describe("MIME type of the file."),
});

export const RequestUploadUrlResponse = zod.object({
  uploadURL: zod.string().url().describe("Presigned GCS URL for PUT upload."),
  objectPath: zod
    .string()
    .describe("Normalized object path. Store this in your database."),
  metadata: zod
    .object({
      name: zod.string().min(1).describe("Original file name."),
      size: zod.number().min(1).describe("File size in bytes."),
      contentType: zod.string().min(1).describe("MIME type of the file."),
    })
    .optional(),
});

/**
 * @summary Serve a public asset from PUBLIC_OBJECT_SEARCH_PATHS
 */
export const GetPublicObjectParams = zod.object({
  filePath: zod.coerce.string(),
});

/**
 * @summary Serve an object entity from PRIVATE_OBJECT_DIR
 */
export const GetStorageObjectParams = zod.object({
  objectPath: zod.coerce.string(),
});

/**
 * @summary Get current authenticated user
 */
export const GetCurrentUserResponse = zod.object({
  clerkId: zod.string(),
  role: zod.enum(["admin", "technician"]),
});

/**
 * @summary List all users (admin only)
 */
export const ListUsersResponseItem = zod.object({
  clerkId: zod.string().describe("Clerk user ID (primary key)"),
  role: zod.enum(["admin", "technician"]).describe("User role"),
  createdAt: zod.coerce.date().describe("When the user first signed in"),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

/**
 * @summary Update user role (admin only)
 */
export const UpdateUserRoleParams = zod.object({
  clerkId: zod.coerce.string(),
});

export const UpdateUserRoleBody = zod.object({
  role: zod.enum(["admin", "technician"]),
});

export const UpdateUserRoleResponse = zod.object({
  clerkId: zod.string().describe("Clerk user ID (primary key)"),
  role: zod.enum(["admin", "technician"]).describe("User role"),
  createdAt: zod.coerce.date().describe("When the user first signed in"),
});
