/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityFeedItem {
  id: string;
  equipmentId: string;
  equipmentName: string;
  status: string;
  note?: string | null;
  photoUrl?: string | null;
  timestamp: Date;
}
