/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

/**
 * User role
 */
export type UserRecordRole =
  (typeof UserRecordRole)[keyof typeof UserRecordRole];

export const UserRecordRole = {
  admin: "admin",
  technician: "technician",
} as const;
