/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface ScanLog {
  id: string;
  equipmentId: string;
  status: string;
  note?: string | null;
  photoUrl?: string | null;
  /** Clerk user ID of the user who performed the scan */
  scannedBy?: string | null;
  timestamp: Date;
}
