/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalyticsSummaryScanActivityItem } from "./analyticsSummaryScanActivityItem";
import type { AnalyticsSummaryStatusBreakdown } from "./analyticsSummaryStatusBreakdown";
import type { AnalyticsSummaryTopProblemEquipmentItem } from "./analyticsSummaryTopProblemEquipmentItem";

export interface AnalyticsSummary {
  totalEquipment: number;
  statusBreakdown: AnalyticsSummaryStatusBreakdown;
  /** Percentage of equipment with up-to-date maintenance (0-100) */
  maintenanceComplianceRate: number;
  scanActivity: AnalyticsSummaryScanActivityItem[];
  topProblemEquipment: AnalyticsSummaryTopProblemEquipmentItem[];
}
