/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Folder {
  id: string;
  name: string;
  createdAt: string;
}

export interface CreateFolderRequest {
  /** @minLength 1 */
  name: string;
}

export interface Equipment {
  /** Auto-generated unique ID */
  id: string;
  /** Equipment name */
  name: string;
  /** Serial number */
  serialNumber?: string | null;
  /** Model name/number */
  model?: string | null;
  /** Manufacturer or brand */
  manufacturer?: string | null;
  /** Date the equipment was purchased */
  purchaseDate?: string | null;
  /** Physical location of the equipment */
  location?: string | null;
  /** Equipment category (e.g. Surgical Instruments, Diagnostic Imaging) */
  category?: string | null;
  /** Folder this equipment belongs to */
  folderId?: string | null;
  /** Last time the QR code was scanned */
  lastSeen?: string | null;
  /** Status set at last scan (ok, issue, maintenance) */
  lastStatus?: string | null;
  /** Date of last maintenance scan */
  lastMaintenanceDate?: string | null;
  /** How often maintenance should occur (days); null means not configured */
  maintenanceIntervalDays?: number | null;
  /** When the equipment was created */
  createdAt: string;
}

export interface CreateEquipmentRequest {
  /** Equipment name */
  name: string;
  /** Serial number */
  serialNumber?: string | null;
  /** Model name/number */
  model?: string | null;
  /** Manufacturer or brand */
  manufacturer?: string | null;
  /** Purchase date */
  purchaseDate?: string | null;
  /** Physical location */
  location?: string | null;
  /** Equipment category */
  category?: string | null;
  /** Optional folder to assign the equipment to */
  folderId?: string | null;
}

export interface UpdateEquipmentRequest {
  /** Maintenance interval in days; null to clear */
  maintenanceIntervalDays?: number | null;
  /** Serial number */
  serialNumber?: string | null;
  /** Model name/number */
  model?: string | null;
  /** Manufacturer or brand */
  manufacturer?: string | null;
  /** Purchase date */
  purchaseDate?: string | null;
  /** Physical location */
  location?: string | null;
  /** Equipment category */
  category?: string | null;
  /** Folder to assign the equipment to; null to unassign */
  folderId?: string | null;
}

/**
 * Status selected after scanning
 */
export type ScanEquipmentRequestStatus =
  (typeof ScanEquipmentRequestStatus)[keyof typeof ScanEquipmentRequestStatus];

export const ScanEquipmentRequestStatus = {
  ok: "ok",
  issue: "issue",
  maintenance: "maintenance",
  sterilized: "sterilized",
} as const;

export interface ScanEquipmentRequest {
  /** Status selected after scanning */
  status: ScanEquipmentRequestStatus;
  /** Optional note about the scan */
  note?: string | null;
  /** Optional photo URL from object storage */
  photoUrl?: string | null;
}

export interface ScanLog {
  id: string;
  equipmentId: string;
  status: string;
  note?: string | null;
  photoUrl?: string | null;
  /** Clerk user ID of the user who performed the scan */
  scannedBy?: string | null;
  timestamp: string;
}

/**
 * User role
 */
export type UserRecordRole =
  (typeof UserRecordRole)[keyof typeof UserRecordRole];

export const UserRecordRole = {
  admin: "admin",
  technician: "technician",
} as const;

export interface UserRecord {
  /** Clerk user ID (primary key) */
  clerkId: string;
  /** User role */
  role: UserRecordRole;
  /** When the user first signed in */
  createdAt: string;
}

export type UserMeRole = (typeof UserMeRole)[keyof typeof UserMeRole];

export const UserMeRole = {
  admin: "admin",
  technician: "technician",
} as const;

export interface UserMe {
  clerkId: string;
  role: UserMeRole;
}

export type UpdateUserRoleRequestRole =
  (typeof UpdateUserRoleRequestRole)[keyof typeof UpdateUserRoleRequestRole];

export const UpdateUserRoleRequestRole = {
  admin: "admin",
  technician: "technician",
} as const;

export interface UpdateUserRoleRequest {
  role: UpdateUserRoleRequestRole;
}

export interface UploadUrlRequest {
  /**
   * Original file name.
   * @minLength 1
   */
  name: string;
  /**
   * File size in bytes.
   * @minimum 1
   */
  size: number;
  /**
   * MIME type of the file.
   * @minLength 1
   */
  contentType: string;
}

export interface UploadUrlResponse {
  /** Presigned GCS URL for PUT upload. */
  uploadURL: string;
  /** Normalized object path. Store this in your database. */
  objectPath: string;
  metadata?: UploadUrlRequest;
}

export type AnalyticsSummaryStatusBreakdown = {
  ok: number;
  issue: number;
  overdue: number;
  inactive: number;
};

export type AnalyticsSummaryScanActivityItem = {
  date: string;
  count: number;
};

export type AnalyticsSummaryTopProblemEquipmentItem = {
  equipmentId: string;
  name: string;
  issueCount: number;
};

export interface AnalyticsSummary {
  totalEquipment: number;
  statusBreakdown: AnalyticsSummaryStatusBreakdown;
  /** Percentage of equipment with up-to-date maintenance (0-100) */
  maintenanceComplianceRate: number;
  scanActivity: AnalyticsSummaryScanActivityItem[];
  topProblemEquipment: AnalyticsSummaryTopProblemEquipmentItem[];
}

export interface ActivityFeedItem {
  id: string;
  equipmentId: string;
  equipmentName: string;
  status: string;
  note?: string | null;
  photoUrl?: string | null;
  timestamp: string;
}

export interface ActivityFeed {
  items: ActivityFeedItem[];
  nextCursor: string | null;
}

export interface BulkDeleteRequest {
  /** @minItems 1 */
  ids: string[];
}

export interface BulkMoveRequest {
  /** @minItems 1 */
  ids: string[];
  /** Target folder ID; null to unassign from any folder */
  folderId: string | null;
}

export interface BulkResult {
  /** Number of items affected */
  affected: number;
}

export interface TransferLog {
  id: string;
  equipmentId: string;
  fromFolderName?: string | null;
  toFolderName?: string | null;
  timestamp: string;
}

export interface ErrorResponse {
  error: string;
}

export type ListLogsParams = {
  /**
   * Opaque pagination cursor returned as nextCursor from a previous response. Do not construct manually.
   */
  cursor?: string;
};
