/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface BulkMoveRequest {
  /** @minItems 1 */
  ids: string[];
  /** Target folder ID; null to unassign from any folder */
  folderId: string | null;
}
