/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Equipment QR Code Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface Equipment {
  /** Auto-generated unique ID */
  id: string;
  /** Equipment name */
  name: string;
  /** Serial number */
  serialNumber?: string | null;
  /** Model name/number */
  model?: string | null;
  /** Manufacturer or brand */
  manufacturer?: string | null;
  /** Date the equipment was purchased */
  purchaseDate?: Date | null;
  /** Physical location of the equipment */
  location?: string | null;
  /** Equipment category (e.g. Surgical Instruments, Diagnostic Imaging) */
  category?: string | null;
  /** Folder this equipment belongs to */
  folderId?: string | null;
  /** Last time the QR code was scanned */
  lastSeen?: Date | null;
  /** Status set at last scan (ok, issue, maintenance) */
  lastStatus?: string | null;
  /** Date of last maintenance scan */
  lastMaintenanceDate?: Date | null;
  /** How often maintenance should occur (days); null means not configured */
  maintenanceIntervalDays?: number | null;
  /** When the equipment was created */
  createdAt: Date;
}
