// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vettrack/Alerts.tsx": () => import("../components/mockups/vettrack/Alerts.tsx"),
  "./components/mockups/vettrack/EquipmentDetails.tsx": () => import("../components/mockups/vettrack/EquipmentDetails.tsx")
};
